# NOTE: Generated By HttpRunner v3.1.11
# FROM: har\mubu_create_doc.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseMubuCreateDoc(HttpRunner):
    config = Config("testcase description").verify(False).base_url("https://api2.mubu.com/v3/api")

    teststeps = [
        Step(
            RunRequest("/v3/api/user/phone_login")
            .post("/user/phone_login")
            .with_headers(
                **{
                    "content-length": "68",
                    "sec-ch-ua": '"Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"',
                    "version": "3.0.0-2.0.0.1921",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67",
                    "data-unique-id": "31693290-1b9c-11ee-9c43-1bd74c1b6a38",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "",
                    "x-request-id": "e1c49c73-95ac-4daf-9324-4ae8edb12dbf",
                    "sec-ch-ua-platform": '"Windows"',
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
                }
            )
            .with_json(
                {
                    "phone": "15036205307",
                    "password": "Luckylhia1024@",
                    "callbackType": 0,
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),

        Step(
            RunRequest("/v3/api/user/profile")
            .post("/user/profile")
            .with_headers(
                **{
                    "content-length": "0",
                    "sec-ch-ua": '"Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"',
                    "sec-ch-ua-platform": '"Windows"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67",
                    "data-unique-id": "31693290-1b9c-11ee-9c43-1bd74c1b6a38",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMjUwOTY4MzIiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2OTEyMDAxMzMsImlhdCI6MTY4ODYwODEzM30.gOtwCHT_M5vkdPMiJ57PFVydEONfu3K2-Gmsuabw-RSrQMqZvWgQdJV2ocpaU8wAlPEES0PaTiV_m9-bPaiHXg",
                    "x-request-id": "6aa56a6f-fe0e-4602-b23e-4b9f9caf8a1a",
                    "version": "3.0.0-2.0.0.1921",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),

        Step(
            RunRequest("/v3/api/activity/five_years/participation")
            .post("/activity/five_years/participation")
            .with_headers(
                **{
                    "content-length": "0",
                    "sec-ch-ua": '"Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"',
                    "sec-ch-ua-platform": '"Windows"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67",
                    "data-unique-id": "31693290-1b9c-11ee-9c43-1bd74c1b6a38",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMjUwOTY4MzIiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2OTEyMDAxMzMsImlhdCI6MTY4ODYwODEzM30.gOtwCHT_M5vkdPMiJ57PFVydEONfu3K2-Gmsuabw-RSrQMqZvWgQdJV2ocpaU8wAlPEES0PaTiV_m9-bPaiHXg",
                    "x-request-id": "1f73d8df-bf26-48d5-b666-7ed327f7cd94",
                    "version": "3.0.0-2.0.0.1921",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 4011)
            .assert_equal("body.msg", "unknown error")
        ),
        Step(
            RunRequest("/v3/api/list/star_relation/get")
            .get("/list/star_relation/get")
            .with_headers(
                **{
                    "sec-ch-ua": '"Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"',
                    "sec-ch-ua-platform": '"Windows"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67",
                    "data-unique-id": "31693290-1b9c-11ee-9c43-1bd74c1b6a38",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMjUwOTY4MzIiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2OTEyMDAxMzMsImlhdCI6MTY4ODYwODEzM30.gOtwCHT_M5vkdPMiJ57PFVydEONfu3K2-Gmsuabw-RSrQMqZvWgQdJV2ocpaU8wAlPEES0PaTiV_m9-bPaiHXg",
                    "x-request-id": "65f59198-0e96-4723-8120-2fdaff6fb1f5",
                    "version": "3.0.0-2.0.0.1921",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/get_all_documents_page")
            .post("/list/get_all_documents_page")
            .with_headers(
                **{
                    "content-length": "12",
                    "sec-ch-ua": '"Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"',
                    "version": "3.0.0-2.0.0.1921",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67",
                    "data-unique-id": "31693290-1b9c-11ee-9c43-1bd74c1b6a38",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMjUwOTY4MzIiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2OTEyMDAxMzMsImlhdCI6MTY4ODYwODEzM30.gOtwCHT_M5vkdPMiJ57PFVydEONfu3K2-Gmsuabw-RSrQMqZvWgQdJV2ocpaU8wAlPEES0PaTiV_m9-bPaiHXg",
                    "x-request-id": "9409ac3e-e85a-4a12-8c2d-00594c027162",
                    "sec-ch-ua-platform": '"Windows"',
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
                }
            )
            .with_json({"start": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/get_user_params")
            .post("/user/get_user_params")
            .with_headers(
                **{
                    "content-length": "0",
                    "sec-ch-ua": '"Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"',
                    "sec-ch-ua-platform": '"Windows"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67",
                    "data-unique-id": "31693290-1b9c-11ee-9c43-1bd74c1b6a38",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMjUwOTY4MzIiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2OTEyMDAxMzMsImlhdCI6MTY4ODYwODEzM30.gOtwCHT_M5vkdPMiJ57PFVydEONfu3K2-Gmsuabw-RSrQMqZvWgQdJV2ocpaU8wAlPEES0PaTiV_m9-bPaiHXg",
                    "x-request-id": "1ded7ce6-791c-4444-af1a-8a7cd9f66155",
                    "version": "3.0.0-2.0.0.1921",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/get_onboard_state")
            .post("/user/get_onboard_state")
            .with_headers(
                **{
                    "content-length": "2",
                    "sec-ch-ua": '"Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"',
                    "version": "3.0.0-2.0.0.1921",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67",
                    "data-unique-id": "31693290-1b9c-11ee-9c43-1bd74c1b6a38",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMjUwOTY4MzIiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2OTEyMDAxMzMsImlhdCI6MTY4ODYwODEzM30.gOtwCHT_M5vkdPMiJ57PFVydEONfu3K2-Gmsuabw-RSrQMqZvWgQdJV2ocpaU8wAlPEES0PaTiV_m9-bPaiHXg",
                    "x-request-id": "601ac9be-e57a-47a1-a3bc-b2598ffee664",
                    "sec-ch-ua-platform": '"Windows"',
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
                }
            )
            .with_json({})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/message/get_message_unread")
            .post("/message/get_message_unread")
            .with_headers(
                **{
                    "content-length": "10",
                    "sec-ch-ua": '"Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"',
                    "version": "3.0.0-2.0.0.1921",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67",
                    "data-unique-id": "31693290-1b9c-11ee-9c43-1bd74c1b6a38",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMjUwOTY4MzIiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2OTEyMDAxMzMsImlhdCI6MTY4ODYwODEzM30.gOtwCHT_M5vkdPMiJ57PFVydEONfu3K2-Gmsuabw-RSrQMqZvWgQdJV2ocpaU8wAlPEES0PaTiV_m9-bPaiHXg",
                    "x-request-id": "e2191734-d0a0-4a7d-ac46-fdba77b33d02",
                    "sec-ch-ua-platform": '"Windows"',
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
                }
            )
            .with_json({"page": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/advertisement/get")
            .post("/advertisement/get")
            .with_headers(
                **{
                    "content-length": "10",
                    "sec-ch-ua": '"Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"',
                    "version": "3.0.0-2.0.0.1921",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67",
                    "data-unique-id": "31693290-1b9c-11ee-9c43-1bd74c1b6a38",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMjUwOTY4MzIiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2OTEyMDAxMzMsImlhdCI6MTY4ODYwODEzM30.gOtwCHT_M5vkdPMiJ57PFVydEONfu3K2-Gmsuabw-RSrQMqZvWgQdJV2ocpaU8wAlPEES0PaTiV_m9-bPaiHXg",
                    "x-request-id": "bee0d9b0-26d7-4f0d-aa9d-50cd2dc7520e",
                    "sec-ch-ua-platform": '"Windows"',
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
                }
            )
            .with_json({"type": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("/list/item_count")
            .with_headers(
                **{
                    "content-length": "30",
                    "sec-ch-ua": '"Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"',
                    "version": "3.0.0-2.0.0.1921",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67",
                    "data-unique-id": "31693290-1b9c-11ee-9c43-1bd74c1b6a38",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMjUwOTY4MzIiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2OTEyMDAxMzMsImlhdCI6MTY4ODYwODEzM30.gOtwCHT_M5vkdPMiJ57PFVydEONfu3K2-Gmsuabw-RSrQMqZvWgQdJV2ocpaU8wAlPEES0PaTiV_m9-bPaiHXg",
                    "x-request-id": "e7190a1d-0368-4692-9bb7-baa177584497",
                    "sec-ch-ua-platform": '"Windows"',
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/notify/new_tip/get")
            .post("/notify/new_tip/get")
            .with_headers(
                **{
                    "content-length": "10",
                    "sec-ch-ua": '"Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"',
                    "version": "3.0.0-2.0.0.1921",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67",
                    "data-unique-id": "31693290-1b9c-11ee-9c43-1bd74c1b6a38",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMjUwOTY4MzIiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2OTEyMDAxMzMsImlhdCI6MTY4ODYwODEzM30.gOtwCHT_M5vkdPMiJ57PFVydEONfu3K2-Gmsuabw-RSrQMqZvWgQdJV2ocpaU8wAlPEES0PaTiV_m9-bPaiHXg",
                    "x-request-id": "501d15cf-48ca-44a1-aa90-558412c5c544",
                    "sec-ch-ua-platform": '"Windows"',
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
                }
            )
            .with_json({"type": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/create_doc")
            .post("/list/create_doc")
            .with_headers(
                **{
                    "content-length": "25",
                    "sec-ch-ua": '"Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"',
                    "version": "3.0.0-2.0.0.1921",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67",
                    "data-unique-id": "31693290-1b9c-11ee-9c43-1bd74c1b6a38",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMjUwOTY4MzIiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2OTEyMDAxMzMsImlhdCI6MTY4ODYwODEzM30.gOtwCHT_M5vkdPMiJ57PFVydEONfu3K2-Gmsuabw-RSrQMqZvWgQdJV2ocpaU8wAlPEES0PaTiV_m9-bPaiHXg",
                    "x-request-id": "bd9c569d-c1ad-43ca-b343-b985608143c3",
                    "sec-ch-ua-platform": '"Windows"',
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
                }
            )
            .with_json({"folderId": "0", "type": 0})

            .extract()
            .with_jmespath("body.data.id", "docId")

            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("/list/item_count")
            .with_headers(
                **{
                    "content-length": "30",
                    "sec-ch-ua": '"Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"',
                    "version": "3.0.0-2.0.0.1921",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67",
                    "data-unique-id": "31693290-1b9c-11ee-9c43-1bd74c1b6a38",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMjUwOTY4MzIiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2OTEyMDAxMzMsImlhdCI6MTY4ODYwODEzM30.gOtwCHT_M5vkdPMiJ57PFVydEONfu3K2-Gmsuabw-RSrQMqZvWgQdJV2ocpaU8wAlPEES0PaTiV_m9-bPaiHXg",
                    "x-request-id": "fab04bc5-29bd-40f1-a131-b1128ed401c2",
                    "sec-ch-ua-platform": '"Windows"',
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/document/edit/get")
            .post("/document/edit/get")
            .with_headers(
                **{
                    "content-length": "37",
                    "sec-ch-ua": '"Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"',
                    "version": "3.0.0-2.0.0.1921",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67",
                    "data-unique-id": "31693290-1b9c-11ee-9c43-1bd74c1b6a38",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMjUwOTY4MzIiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2OTEyMDAxMzMsImlhdCI6MTY4ODYwODEzM30.gOtwCHT_M5vkdPMiJ57PFVydEONfu3K2-Gmsuabw-RSrQMqZvWgQdJV2ocpaU8wAlPEES0PaTiV_m9-bPaiHXg",
                    "x-request-id": "fb4db0c9-7fa4-42ce-93bc-0ee4563c54f4",
                    "sec-ch-ua-platform": '"Windows"',
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
                }
            )
            .with_json({"docId": "${docId}", "password": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/register")
            .get("/colla/register")
            .with_headers(
                **{
                    "sec-ch-ua": '"Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67",
                    "data-unique-id": "31693290-1b9c-11ee-9c43-1bd74c1b6a38",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMjUwOTY4MzIiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2OTEyMDAxMzMsImlhdCI6MTY4ODYwODEzM30.gOtwCHT_M5vkdPMiJ57PFVydEONfu3K2-Gmsuabw-RSrQMqZvWgQdJV2ocpaU8wAlPEES0PaTiV_m9-bPaiHXg",
                    "x-request-id": "7e55852a-cc8e-4c00-9558-f80192d43ac9",
                    "sec-ch-ua-platform": '"Windows"',
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/events")
            .post("/colla/events")
            .with_headers(
                **{
                    "content-length": "93",
                    "sec-ch-ua": '"Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67",
                    "data-unique-id": "31693290-1b9c-11ee-9c43-1bd74c1b6a38",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMjUwOTY4MzIiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2OTEyMDAxMzMsImlhdCI6MTY4ODYwODEzM30.gOtwCHT_M5vkdPMiJ57PFVydEONfu3K2-Gmsuabw-RSrQMqZvWgQdJV2ocpaU8wAlPEES0PaTiV_m9-bPaiHXg",
                    "x-request-id": "44daa8cf-68e6-49a8-a254-43f4a4a231cb",
                    "sec-ch-ua-platform": '"Windows"',
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
                }
            )
            .with_json(
                {
                    "reqId": "1",
                    "type": "USER_HEARTBEAT",
                    "memberId": "762090730565653",
                    "documentId": "${docId}",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/doc/list")
            .post("/refer/doc/list")
            .with_headers(
                **{
                    "content-length": "29",
                    "sec-ch-ua": '"Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67",
                    "data-unique-id": "31693290-1b9c-11ee-9c43-1bd74c1b6a38",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMjUwOTY4MzIiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2OTEyMDAxMzMsImlhdCI6MTY4ODYwODEzM30.gOtwCHT_M5vkdPMiJ57PFVydEONfu3K2-Gmsuabw-RSrQMqZvWgQdJV2ocpaU8wAlPEES0PaTiV_m9-bPaiHXg",
                    "x-request-id": "04869155-ff6f-4bb1-9f6f-e7b85ce9c0c7",
                    "sec-ch-ua-platform": '"Windows"',
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
                }
            )
            .with_json({"targetDocId": "${docId}"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/node/count")
            .post("/refer/node/count")
            .with_headers(
                **{
                    "content-length": "29",
                    "sec-ch-ua": '"Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"',
                    "version": "3.0.0-2.0.0.1921",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67",
                    "data-unique-id": "31693290-1b9c-11ee-9c43-1bd74c1b6a38",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMjUwOTY4MzIiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2OTEyMDAxMzMsImlhdCI6MTY4ODYwODEzM30.gOtwCHT_M5vkdPMiJ57PFVydEONfu3K2-Gmsuabw-RSrQMqZvWgQdJV2ocpaU8wAlPEES0PaTiV_m9-bPaiHXg",
                    "x-request-id": "eb1c5124-9428-46a0-9ba0-9398e081dc54",
                    "sec-ch-ua-platform": '"Windows"',
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
                }
            )
            .with_json({"targetDocId": "${docId}"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/members_v2")
            .post("/colla/members_v2")
            .with_headers(
                **{
                    "content-length": "57",
                    "sec-ch-ua": '"Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67",
                    "data-unique-id": "31693290-1b9c-11ee-9c43-1bd74c1b6a38",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMjUwOTY4MzIiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2OTEyMDAxMzMsImlhdCI6MTY4ODYwODEzM30.gOtwCHT_M5vkdPMiJ57PFVydEONfu3K2-Gmsuabw-RSrQMqZvWgQdJV2ocpaU8wAlPEES0PaTiV_m9-bPaiHXg",
                    "request-id": "members:762090730565653:1688608165626",
                    "x-request-id": "00157837-bc55-47e9-ac2c-f9515e5e0dfd",
                    "sec-ch-ua-platform": '"Windows"',
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
                }
            )
            .with_json({"memberId": "762090730565653", "documentId": "${docId}"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/events")
            .post("/colla/events")
            .with_headers(
                **{
                    "content-length": "205",
                    "sec-ch-ua": '"Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67",
                    "data-unique-id": "31693290-1b9c-11ee-9c43-1bd74c1b6a38",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMjUwOTY4MzIiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2OTEyMDAxMzMsImlhdCI6MTY4ODYwODEzM30.gOtwCHT_M5vkdPMiJ57PFVydEONfu3K2-Gmsuabw-RSrQMqZvWgQdJV2ocpaU8wAlPEES0PaTiV_m9-bPaiHXg",
                    "x-request-id": "90b3927f-650d-438a-8c34-e360d072ed63",
                    "sec-ch-ua-platform": '"Windows"',
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
                }
            )
            .with_json(
                {
                    "reqId": "2",
                    "memberId": "762090730565653",
                    "type": "CURSOR",
                    "documentId": "${docId}",
                    "cursor": {
                        "anchorId": "",
                        "anchorOffset": 0,
                        "anchorNodeType": "title",
                        "focusId": "",
                        "focusOffset": 0,
                        "focusNodeType": "title",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/events")
            .post("/colla/events")
            .with_headers(
                **{
                    "content-length": "148",
                    "sec-ch-ua": '"Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67",
                    "data-unique-id": "31693290-1b9c-11ee-9c43-1bd74c1b6a38",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMjUwOTY4MzIiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2OTEyMDAxMzMsImlhdCI6MTY4ODYwODEzM30.gOtwCHT_M5vkdPMiJ57PFVydEONfu3K2-Gmsuabw-RSrQMqZvWgQdJV2ocpaU8wAlPEES0PaTiV_m9-bPaiHXg",
                    "x-request-id": "86e88258-d014-4d5b-bf1c-3161790be410",
                    "sec-ch-ua-platform": '"Windows"',
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
                }
            )
            .with_json(
                {
                    "memberId": "762090730565653",
                    "type": "CHANGE",
                    "version": 0,
                    "documentId": "${docId}",
                    "events": [
                        {"name": "nameChanged", "title": "demo", "original": ""}
                    ],
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/events")
            .post("/colla/events")
            .with_headers(
                **{
                    "content-length": "249",
                    "sec-ch-ua": '"Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67",
                    "data-unique-id": "31693290-1b9c-11ee-9c43-1bd74c1b6a38",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMjUwOTY4MzIiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2OTEyMDAxMzMsImlhdCI6MTY4ODYwODEzM30.gOtwCHT_M5vkdPMiJ57PFVydEONfu3K2-Gmsuabw-RSrQMqZvWgQdJV2ocpaU8wAlPEES0PaTiV_m9-bPaiHXg",
                    "x-request-id": "18525b04-190a-4af0-819f-d60d453f643d",
                    "sec-ch-ua-platform": '"Windows"',
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
                }
            )
            .with_json(
                {
                    "memberId": "762090730565653",
                    "type": "CHANGE",
                    "version": 1,
                    "documentId": "${docId}",
                    "events": [
                        {
                            "name": "create",
                            "created": [
                                {
                                    "index": 0,
                                    "parentId": None,
                                    "node": {
                                        "id": "cU86xZNUkO",
                                        "text": "",
                                        "modified": 1688608171876,
                                        "children": [],
                                    },
                                    "path": ["nodes", 0],
                                }
                            ],
                        }
                    ],
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/search_refers")
            .post("/refer/search_refers")
            .with_headers(
                **{
                    "content-length": "52",
                    "sec-ch-ua": '"Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67",
                    "data-unique-id": "31693290-1b9c-11ee-9c43-1bd74c1b6a38",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMjUwOTY4MzIiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2OTEyMDAxMzMsImlhdCI6MTY4ODYwODEzM30.gOtwCHT_M5vkdPMiJ57PFVydEONfu3K2-Gmsuabw-RSrQMqZvWgQdJV2ocpaU8wAlPEES0PaTiV_m9-bPaiHXg",
                    "x-request-id": "1542eae7-869b-4877-8cdc-71cf7c3010e8",
                    "sec-ch-ua-platform": '"Windows"',
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
                }
            )
            .with_json({"docId": "${docId}", "keywords": "demo", "option": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/events")
            .post("/colla/events")
            .with_headers(
                **{
                    "content-length": "445",
                    "sec-ch-ua": '"Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67",
                    "data-unique-id": "31693290-1b9c-11ee-9c43-1bd74c1b6a38",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMjUwOTY4MzIiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2OTEyMDAxMzMsImlhdCI6MTY4ODYwODEzM30.gOtwCHT_M5vkdPMiJ57PFVydEONfu3K2-Gmsuabw-RSrQMqZvWgQdJV2ocpaU8wAlPEES0PaTiV_m9-bPaiHXg",
                    "x-request-id": "74d41a44-79de-4013-83b5-0ca7f8fb2cfd",
                    "sec-ch-ua-platform": '"Windows"',
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
                }
            )
            .with_json(
                {
                    "memberId": "762090730565653",
                    "type": "CHANGE",
                    "version": 2,
                    "documentId": "${docId}",
                    "events": [
                        {
                            "name": "update",
                            "updated": [
                                {
                                    "updated": {
                                        "id": "cU86xZNUkO",
                                        "text": "<span>1</span>",
                                        "modified": 1688608172773,
                                    },
                                    "original": {
                                        "id": "cU86xZNUkO",
                                        "text": "",
                                        "modified": 1688608171876,
                                    },
                                    "path": ["nodes", 0],
                                }
                            ],
                        },
                        {
                            "name": "create",
                            "created": [
                                {
                                    "index": 1,
                                    "parentId": None,
                                    "node": {
                                        "id": "ilfpKPuVCS",
                                        "text": "",
                                        "modified": 1688608173030,
                                        "children": [],
                                    },
                                    "path": ["nodes", 1],
                                }
                            ],
                        },
                    ],
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/events")
            .post("/colla/events")
            .with_headers(
                **{
                    "content-length": "292",
                    "sec-ch-ua": '"Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67",
                    "data-unique-id": "31693290-1b9c-11ee-9c43-1bd74c1b6a38",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMjUwOTY4MzIiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2OTEyMDAxMzMsImlhdCI6MTY4ODYwODEzM30.gOtwCHT_M5vkdPMiJ57PFVydEONfu3K2-Gmsuabw-RSrQMqZvWgQdJV2ocpaU8wAlPEES0PaTiV_m9-bPaiHXg",
                    "x-request-id": "eaef2d6b-4102-4f67-9e84-7efc4c02a79f",
                    "sec-ch-ua-platform": '"Windows"',
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
                }
            )
            .with_json(
                {
                    "memberId": "762090730565653",
                    "type": "CHANGE",
                    "version": 3,
                    "documentId": "${docId}",
                    "events": [
                        {
                            "name": "update",
                            "updated": [
                                {
                                    "updated": {
                                        "id": "ilfpKPuVCS",
                                        "text": "<span>2</span>",
                                        "modified": 1688608173457,
                                    },
                                    "original": {
                                        "id": "ilfpKPuVCS",
                                        "text": "",
                                        "modified": 1688608173030,
                                    },
                                    "path": ["nodes", 1],
                                }
                            ],
                        }
                    ],
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),

    ]


if __name__ == "__main__":
    TestCaseMubuCreateDoc().test_start()
